### ISSUE TITLE
Publish beta version on npm

### ISSUE THREAD

**Issue by moimael** [webpack-contrib/uglifyjs-webpack-plugin#103]
HI,

Would it be possible to publish the 1.0.0 beta version of the plugin to npm ? We have issues with uglifyjs and es6 and I'd love to use this version.

Thanks !

**Comment by michael-ciniawsky** [comment]
```
npm i -D uglifyjs-webpack-plugin@beta
```

**Comment by moimael** [comment]
Thanks ! But now no matter what i do i get errors because of es6 like
```
ERROR in js/0.56d623e774be5ea87459.js from UglifyJs
Unexpected token punc «(», expected punc «:» [js/0.56d623e774be5ea87459.js:1,22]

ERROR in js/admin_vendor.73bac58a9897a1015eea.js from UglifyJs
Invalid assignment [js/admin_vendor.73bac58a9897a1015eea.js:1,39]
```

**Comment by wood1986** [comment]
Hey @michael-ciniawsky and @moimael 

The main problem is ["uglifyjs-webpack-plugin": "^0.4.6"](https://github.com/webpack/webpack/blob/master/package.json) in the package.json in webpack

According to [semver](https://docs.npmjs.com/misc/semver), `^0.4.6 := >=0.4.6 <0.5.0`. Because of the leading zero, webpack will never hook the beta version.

So after running `npm i -D uglifyjs-webpack-plugin@beta`, you need to do one more step which is `rm -rf node_modules/webpack/node_modules/uglifyjs-webpack-plugin`
