### ISSUE TITLE
[Bug] `nameCache` doesn't get applied (`uglifyOptions.nameCache`)

### ISSUE THREAD

**Issue by Twilrom** [webpack-contrib/uglifyjs-webpack-plugin#130]
In buildDefaultUglifyOptions every option except sourceMap and nameCache are handled. sourceMap has a comment that it's being ignored, but nameCache is strangely absent. Is there a reason for that, or is it simply an oversight?

**Comment by michael-ciniawsky** [comment]
`nameCache` isn't used by default (`null`), but you can use it as all `uglify` options are supported by the plugin.

**Comment by Twilrom** [comment]
No. It's not passed through.

**Comment by simonjoom** [comment]
yes i found the same issue, 
here the code to change pass this resolve it 👍 
without this the chunks are not properly compressed because the mangles property deleted between them


in the code minify.js of uglifyjs-webpack-plugin  
var buildDefaultUglifyOptions = function buildDefaultUglifyOptions(_ref) {
  var ecma = _ref.ecma,
      warnings = _ref.warnings,
      _ref$parse = _ref.parse,
      parse = _ref$parse === undefined ? {} : _ref$parse,
      _ref$compress = _ref.compress,
      compress = _ref$compress === undefined ? {} : _ref$compress,
      mangle = _ref.mangle,
      output = _ref.output,
      toplevel = _ref.toplevel,
      ie8 = _ref.ie8,
      nameCache = _ref.nameCache;

  return {
    ecma,
    warnings,
    parse,
    compress,
    mangle: mangle == null ? true : mangle,
    // Ignoring sourcemap from options
    sourceMap: null,
    output: Object.assign({
      comments: /^\**!|@preserve|@license|@cc_on/,
      beautify: false,
      semicolons: true,
      shebang: true
    }, output),
    toplevel,
    ie8,
    nameCache
  };
};

**Comment by evilebottnawi** [comment]
@simonjoom can you create minimum reproducible test repo?
