### ISSUE TITLE
Conceptual question: Why is this is a plugin?

### ISSUE THREAD

**Issue by AriaFallah** [webpack-contrib/uglifyjs-webpack-plugin#20]
I'm just trying to better understand the Webpack ecosystem, and the way I had the difference between a plugin and a loader arranged in my head was that a loader is a `String -> String` transformation, and plugins are used when you are **adding** functionality to Webpack.

Given that definition, why is this a plugin instead of a loader?

* Is my definition wrong?
* Am I wrong in assuming that uglifying a file is a `String -> String` transformation
* Is it just a plugin for legacy reasons?
* Is it because it ideally would be a loader, but it requires some plugin functionality that loaders can't do?

**Comment by michael-ciniawsky** [comment]
The reason this is a plugin instead of a loader (while possible) is mainly because it operates on the whole bundle (compilation) and not on a per module/chunk/file basis like a loader does.
Loaders run depending on the file extension specified in `{ test: /\.ext/ }` and transform the contents per `chunk/file`, the loader chain is called for each file separately, which means that for e.g uglify isn't able to apply all optimizations possible on the whole bundle since it's missing context, while a plugin has access to the whole `compilation`. In short loader and plugins are different in scope and context. 😛 

> Am I wrong in assuming that uglifying a file is a String -> String transformation

Wrll basically thats true, but uglifying/minification is more an AST (Abstract Syntax Tree) transformation, it takes in a `{String}` parses the string to an AST,applies various optimizations on the AST (whitespace removal, deduplication, dead code removal, comments removal...) and returns a `{String}` by stringifying the AST afterwards.
 
In terms of loaders not exclusively, exporting a module or transforming an AST are also very common, think of it as a function chain with an API (this) providing webpack specifics

**loader.js**
```js
module.exports = function (source, sourcemap) {
   console.log(this) // Loader API

   ...Your transformations...

   return this.async(Error, result.source, result.sourcemap)
}
```

For more information on Parsers/AST/Minifier see [parser](https://github.com/babel/babylon), [ast](https://github.com/estree/estree), [minififier](https://github.com/babel/babili) [(plugin based, modular)](https://github.com/thejameskyle/babel-handbook)
For more information on loaders/plugins see the [official documentation for developers](https://webpack.js.org/development/)

**Comment by AriaFallah** [comment]
@michael-ciniawsky Thanks a lot 😄. Also I assume stuff like generating source maps can't be done with just loaders.

**Comment by michael-ciniawsky** [comment]
Depending if the lib you use inside a loader is able to generate sourcemaps,`postcss-loader` , 'coffee-loader` for e.g (can) generate their maps :). Getting the source URL's right is a common problem

**Comment by michael-ciniawsky** [comment]
```js
function loader (source, sourcemap) {
   transform(source).then((result) => {
       source = result.source
       sourcemap = result.sourcemap || sourcemap

       this.async(Error, source, sourcemap)
   }) 
}
```
