### ISSUE TITLE
ssri upgrade - security advisory

### ISSUE THREAD

**Issue by FrailWords** [webpack-contrib/uglifyjs-webpack-plugin#246]
There's a security advisory to upgrade ssri to >= 5.2.2 (right now it is at 5.0.0).

https://nodesecurity.io/advisories/565

![ssri_vulnerability](https://user-images.githubusercontent.com/1758326/36803117-fd7590c6-1cb6-11e8-96f9-a6e03a99f18a.jpg)

**Comment by evilebottnawi** [comment]
@FrailWords please recreate this issue in `cacache` package. it is dependecy

**Comment by FrailWords** [comment]
@evilebottnawi Looks like there's already an issue there.  Apologies for not looking it up first. 

https://github.com/zkat/cacache/issues/124

**Comment by zkat** [comment]
For those dropping in, I wanna note: `cacache` and anything that uses it is _not_ vulnerable to the issue in this advisory, because it does not use strict mode (which is where the regex happens). Likewise, it's unlikely that anyone using `ssri` for dealing with npm-compatible SRIs will run into this, because npm itself needs non-strict parsing.

**Comment by michael-ciniawsky** [comment]
Released in [`v1.2.3`](https://github.com/webpack-contrib/uglifyjs-webpack-plugin/releases/tag/v1.2.3) 🎉
