### ISSUE TITLE
output.comments default behavior changed

### ISSUE THREAD

**Issue by owiber** [webpack-contrib/uglifyjs-webpack-plugin#289]
In 1.2.4, it looks like the default behavior of `output.comments` changed from `false` to `/^\**!|@preserve|@license|@cc_on/` if `extractComments` is disabled (which is the default case).

This seems to be a result of: https://github.com/webpack-contrib/uglifyjs-webpack-plugin/pull/250.

Was this intentional? For large files, the new default behavior has quite a large negative impact on speed and memory usage.

**Comment by evilebottnawi** [comment]
Yes it is expected, we should respect copyright and licenses of other developers. Also itry to read all license in you application, perhaps some of them are not in MIT and other you **should** provide license. Otherwise, you violate the license and the law. Therefore, the behavior has been changed.

You your known all you licenses and understand that they can be removed, use the options

```
uglifyOptions: {
        output: {
          comments: false
        }    
}
```

Also you can use `extractComments: true` it is extract comment to separable file. Thanks!
