### ISSUE TITLE
uglify-es is no longer maintained

### ISSUE THREAD

**Issue by radum** [webpack-contrib/uglifyjs-webpack-plugin#349]
According to the maintainer `uglify-es` is no longer [maintained](https://github.com/mishoo/UglifyJS2/issues/3156#issuecomment-392943058) and uglify-js does not support ES6+

If we use Babel with preset-env and we target latest browsers, this will not work as expected, is it?

This is also used when webpack is in production mode, so might be a bit confusing in terms of your output. Considering that the main master branch is moving fwd with bug fixes and so on. Harmony is way behind of all this.

Is there any existing plan to move to something else?

**Comment by evilebottnawi** [comment]
Use https://github.com/webpack-contrib/terser-webpack-plugin, next major will be switched back to uglifyjs

**Comment by evilebottnawi** [comment]
Also in near future will be release babel-minify-webpack-plugin

**Comment by thw0rted** [comment]
Any updated advice for users at the end of 2018?  I'm trying to switch to ES6 output and came across this issue while researching why it breaks my build.  As far as I can tell I have latest (stable) webpack and `uglifyjs-webpack-plugin`.  It looks like `uglify-es` and its corresponding webpack plugin are abandoned, and `babel-minify-webpack-plugin` has few downloads and no updates since last March.

Should I switch to one of these abandoned projects? Should I start using beta webpack, assuming there are decent builds of v5 available?  Did the roadmap change again?

**Comment by evilebottnawi** [comment]
@thw0rted webpack already use `terser` and next version will be use `terser` too, he support `es5` and `es6`and other new syntax https://github.com/webpack-contrib/terser-webpack-plugin

**Comment by thw0rted** [comment]
OK, I was manually specifying an instance of uglifyjs-webpack-plugin in my config so I have switched that out for an instance of terser-webpack-plugin, which seems to Just Work.  Thanks!
